api = "0.8"

[buildpack]
  id = "paketo-buildpacks/python"
  name = "Paketo Python Buildpack (Plotly fork)"
  version = "5.2"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "5.4.0b2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/pipenv"
    version = "1.21.0"

  [[order.group]]
    id = "paketo-buildpacks/pipenv-install"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "5.4.0b2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/pip-install"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/miniconda"
    version = "0.9.0"

  [[order.group]]
    id = "paketo-buildpacks/conda-env-update"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "5.4.0b2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/poetry-run"
    version = "0.4.22"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "5.4.0b2"

  [[order.group]]
    id = "paketo-buildpacks/pip"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/poetry"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/poetry-install"
    version = "5.3-sp"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.3"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.3"

  [[order.group]]
    id = "paketo-buildpacks/cpython"
    version = "5.4.0b2"

  [[order.group]]
    id = "paketo-buildpacks/python-start"
    version = "0.14.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.4"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.3"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.2"
